#!/usr/bin/env python
'''
Publish commands to the salt system from the command line on the master.
'''
from salt.scripts import salt_cp
#from salt.scripts import salt_ncp


if __name__ == '__main__':
    #salt_ncp()
    salt_cp()
