# This file was auto-generated by salt's setup

from salt.version import SaltStackVersion

#major,minor,bugfix,mbugfix,pre_type,pre_num,noc,sha
#__saltstack_version__ = SaltStackVersion('2019', 1, 7, 0, 'JD.PKG', 1, 0, None)
__saltstack_version__ = SaltStackVersion(2019, 8, 14, 0, u'', 0, 0, None)
